

#define CONTENTS_MAX_LEN 512

#define REQ_ROOM_CREATE_CODE 8
#define REQ_ROOM_DELETE_CODE 1 
#define REQ_ROOM_CONNECT_CODE 2 
#define REQ_SEND_CHAT_CODE 3
#define REQ_ROOM_INVITE_CODE 4
#define REQ_REGISTER_CODE 5
#define REQ_ROOM_LIST_CODE 6
#define REQ_USER_LIST_CODE 7
#define REQ_FILE_UPLOAD_CONTENT_CODE 10
#define REQ_FILE_DOWNLOAD 9 

void handle_res(int sock);